### ISSUE TITLE
Challenge Fragment: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by wvictor-rr** [praekeltfoundation/gem-bbb-indo#265]
@rjacobs31 I started up the app, logged in, and immediately scrolled to tips. While waiting for a tip article to load, it crashed with the below exception. I think it's async code in the Challenges fragment thats trying to handle destroyed fragments/activities.

I'm on the latest `develop`.

```
E/CrashlyticsCore: Failed to execute task.
                   java.lang.InterruptedException
                       at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:391)
                       at java.util.concurrent.FutureTask.get(FutureTask.java:163)
                       at com.crashlytics.android.core.CrashlyticsExecutorServiceWrapper.executeSyncLoggingException(CrashlyticsExecutorServiceWrapper.java:47)
                       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:251)
                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
                       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:66)
                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                       at java.lang.Thread.run(Thread.java:761)
E/AndroidRuntime: FATAL EXCEPTION: RxNewThreadScheduler-21
                  Process: org.gem.indo.dooit, PID: 2331
                  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
                      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                      at java.lang.Thread.run(Thread.java:761)
                   Caused by: rx.exceptions.OnErrorNotImplementedException: Can not perform this action after onSaveInstanceState
                      at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:374)
                      at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:371)
                      at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                      at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
                      at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                      at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:204)
                      at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
                      at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
                      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                      at java.lang.Thread.run(Thread.java:761) 
                   Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                      at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1538)
                      at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1556)
                      at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:696)
                      at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:662)
                      at org.gem.indo.dooit.views.main.fragments.challenge.ChallengeFragment.loadTypeFragment(ChallengeFragment.java:126)
                      at org.gem.indo.dooit.views.main.fragments.challenge.ChallengeFragment.access$000(ChallengeFragment.java:41)
                      at org.gem.indo.dooit.views.main.fragments.challenge.ChallengeFragment$2.call(ChallengeFragment.java:162)
                      at org.gem.indo.dooit.views.main.fragments.challenge.ChallengeFragment$2.call(ChallengeFragment.java:159)
                      at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
                      at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                      at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215) 
                      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                      at java.lang.Thread.run(Thread.java:761) 
```

**Comment by wvictor-rr** [comment]
@rjacobs31 @FredJEhlers Is this issue still valid?

**Comment by FredJEhlers** [comment]
@wvictor-rr unable to recreate the bug, I believe it is fixed
