### ISSUE TITLE
Crash on Profile Image Activity

### ISSUE THREAD

**Issue by wvictor-rr** [praekeltfoundation/gem-bbb-indo#440]
There is a case where the `ProfileImageActivity` can crash.

```
Caused by java.lang.NullPointerException
       at org.gem.indo.dooit.views.onboarding.ProfileImageActivity$1.call(ProfileImageActivity.java:109)
       at org.gem.indo.dooit.views.onboarding.ProfileImageActivity$1.call(ProfileImageActivity.java:105)
```

The stacktrace does not indicate which reference is null. It is either the user or imageUri that is unexpectedly null.

Version 0.0.13

[See line 109 of ProfileImageActivity](https://github.com/praekeltfoundation/gem-bbb-indo/blob/develop/app/src/main/java/org/gem/indo/dooit/views/onboarding/ProfileImageActivity.java#L109)

[See stacktrace in Crashlytics issue #30](https://www.fabric.io/retro-rabbit/android/apps/org.gem.indo.dooit/issues/587eaa830aeb16625b39a252)

**Comment by wvictor-rr** [comment]
There is a larger problem afoot. There are cases where the imageUri is null, even though the camera has taken a picture, which aren't being handled.

**Comment by wvictor-rr** [comment]
@FredJEhlers Send Crashlytics a message when ImageUri is null
