### ISSUE TITLE
Crash on weeks left, Goal date is null

### ISSUE THREAD

**Issue by wvictor-rr** [praekeltfoundation/gem-bbb-indo#457]
Goal date was null when Bot requested weeks left.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Date org.joda.time.LocalDate.toDate()' on a null object reference
       at org.gem.indo.dooit.models.goal.Goal.getWeeksLeft(Goal.java:237)
       at org.gem.indo.dooit.controllers.goal.GoalBotController.resolveParam(GoalBotController.java:110)
       at org.gem.indo.dooit.views.main.fragments.bot.viewholders.TextViewHolder.populateModel(TextViewHolder.java:75)
       at org.gem.indo.dooit.views.main.fragments.bot.viewholders.BaseBotViewHolder.populate(BaseBotViewHolder.java:42)
       at org.gem.indo.dooit.views.main.fragments.bot.viewholders.TextViewHolder.populate(TextViewHolder.java:51)
       at org.gem.indo.dooit.views.main.fragments.bot.viewholders.TextViewHolder.populate(TextViewHolder.java:29)
       at org.gem.indo.dooit.views.main.fragments.bot.adapters.BotAdapter.onBindViewHolder(BotAdapter.java:110)
       at org.gem.indo.dooit.views.main.fragments.bot.adapters.BotAdapter.onBindViewHolder(BotAdapter.java:38)
```

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/retro-rabbit/android/apps/org.gem.indo.dooit/issues/5881a53d0aeb16625b504325](https://fabric.io/retro-rabbit/android/apps/org.gem.indo.dooit/issues/5881a53d0aeb16625b504325)

1 Hour

**Comment by wvictor-rr** [comment]
Inserted Crashlytics logs to help troubleshoot the issue in the future
